---
apiVersion: v1
kind: Service
metadata:
  name: app-1
  namespace: dev
  labels:
    app: app-1
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8888
      protocol: TCP
      nodePort: 30080
  selector:
    app: app-1
---
