---
apiVersion: v1
kind: Service
metadata:
  name: app-1
  namespace: dev
  labels:
    app: app-1
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: app-1
  type: ClusterIP
---